name: "Continuous Integration Payment API"

on:
  push:
    branches:
      - "Project-PaymentAPI"
  pull_request:

jobs:
  phpcs:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out code"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - name: "Install PHP_CodeSniffer"
        run: "|
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          chmod +x phpcs.phar
          sudo mv phpcs.phar /usr/local/bin/phpcs
          phpcs --version"

      - name: "Run PHP_CodeSniffer"
        run: "|
          phpcs --standard=phpcs.xml --ignore=*/vendor/* --report=summary ."
